apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  containers:
  - name: mobincontainer1
    image: smobinulla/nginxmob:v1
    ports:
    - containerPort: 80
  - name: mobincontainer2
    image: smobinulla/nginxmob:v2
    command: ['sh', '-c', 'while true; do echo "Hello from sidecar container" >> /var/log/sidecar.log; sleep 5; done']
