apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobin-deployment
  labels:
    app: webapp1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: mobinwebapp1
        image: smobinulla/nginxmob:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mobin-webapp1-service
  labels:
    app: webapp1
spec:
  selector:
    app: webapp1
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30033
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: deamon1
spec:
 selector:
   matchLabels:
     app: webapp1
 template:
   metadata:
     name: webapppod
     labels:
       app: webapp1
   spec:
     containers:
       - image: grafana/grafana
         name: grafanacon
         ports:
         - containerPort: 3000
---
