apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
  labels:
    name: raw-volume-testing
spec:
  containers:
    - image: nginx:latest
      name: test-container
      volumeMounts:
      - mountPath: /usr/share/nginx/html/
        name: test-volume
  volumes:
  - name: test-volume
    awsElasticBlockStore:
      volumeID: vol-0b1ff27cd5b6fe3f3
      fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    name: raw-volume-testing
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ebsloadbalance
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    name: raw-volume-testing
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
