apiVersion: v1
kind: Pod
metadata:
  name: test-ebs1
  labels:
    name: git-volume-test
spec:
  containers:
    - image: nginx:latest
      name: test-container
      volumeMounts:
      - mountPath: /usr/share/nginx/html/
        name: test-volume
  volumes:
  - name: test-volume
    gitRepo:
      repository: https://github.com/smobinulla/spearing.git
      revision: master
      directory: .
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    name: git-volume-test
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ebsloadbalance
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    name: git-volume-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
