apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
  labels:
    name: nginx
spec:
  containers:
  - image: nginx:latest
    name: web-server
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/
  - name: git-sync
    image: k8s.gcr.io/git-sync:v3.0.1
    volumeMounts:
    - name: html
      mountPath: /tmp/git/
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/smobinulla/spearing.git
    - name: GIT_SYNC_BRANCH
      value: master
    - name: GIT_SYNC_DEST
      value: html
  volumes:
  - name: html
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ebsloadbalance
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    name: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
