apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deploy
spec:
  selector:
    matchLabels:
      run: hpa-deploy
  replicas: 3
  template:
    metadata:
      labels:
        run: hpa-deploy
    spec:
      containers:
      - name: hpa-deploy
        image: smobinulla/nginxmob:v3
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 400m
            memory: "400Mi"
          requests:
            cpu: 100m
            memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-deploy
  labels:
    run: hpa-deploy
spec:
  ports:
  - port: 80
  selector:
    run: hpa-deploy
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30033
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deploy
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
