---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness
  labels:
    app: liveness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: liveness
  template:
    metadata:
      labels:
        app: liveness
    spec:
      containers:
        - name: webapp1con
          image: smobinulla/nginxmob:v1
          ports:
          - containerPort: 80
          livenessProbe:
            exec:
              command:
              - cat
              - /var/www/html/index.html
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 2
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: livenesssvc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: liveness
