---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness1
  labels:
    app: liveness1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: liveness1
  template:
    metadata:
      labels:
        app: liveness1
    spec:
      containers:
        - name: webapp2con
          image: smobinulla/nginxmob:primecare
          ports:
          - containerPort: 80
          liveness1Probe:
            exec:
              command:
              - cat
              - /var/www/html/index.html
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 2
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: webapp2cluster
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: liveness1

---
apiVersion: v1
kind: Service
metadata:
  name: webapp2nodeportsvc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: liveness1

---
apiVersion: v1
kind: Service
metadata:
  name: webapp2loadbalsvc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: liveness1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 
