apiVersion: v1
kind: PersistentVolume
metadata: 
  name: aws-pv2
  labels:
    type: aws-pv2
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-082684baad4dee5ca
    fsType: ext4
