apiVersion: v1
kind: PersistentVolume
metadata: 
  name: aws-pv3
  labels:
    type: aws-pv3
spec:
  storageClassName: io1
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 4Gi
  accessModes:
    - ReadOnlyMany
  awsElasticBlockStore:
    volumeID: vol-006ba9cc446d3e5d9
    fsType: ext4
