apiVersion: v1
kind: PersistentVolume
metadata: 
  name: aws-pv3
  labels:
    type: aws-pv3
spec:
  storageClassName: io1
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 6Gi
  accessModes:
    - ReadOnlyMany
  awsElasticBlockStore:
    volumeID: vol-0c6b89f5b31b1542a
    fsType: ext4
