---
kind: Namespace
apiVersion: v1
metadata:
  name: javans

---
apiVersion: v1
kind: Pod
metadata:
  name: java-pod
  namespace: javans
  labels:
    app: javaapp
spec:
  containers:
    - name: javacontainer
      image: dockerhandson/java-web-app
      ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
  namespace: javans
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: javaapp

---
apiVersion: v1
kind: Service
metadata:
  name: javaappnodeport
  namespace: javans
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30033

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: javaapp
  namespace: javans
spec:
  replicas: 5
  selector:
    app: javaapp
  template:
    metadata:
      name: java-pod
      labels:
        app: javaapp
    spec:
      containers:
        - name: javacontainer
          image: dockerhandson/java-web-app
          ports:
          - containerPort: 8080
---
