---
kind: Namespace
apiVersion: v1
metadata:
  name: v2ns

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp2
  namespace: v2ns
  labels:
    app: webapp2
spec:
  containers:
    - name: javacontainer
      image: smobinulla/nginxmob:v2
      ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
  namespace: v2ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webapp2

---
apiVersion: v1
kind: Service
metadata:
  name: webapp2nodeport
  namespace: v2ns
spec:
  type: NodePort
  selector:
    app: webapp2
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30034

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp2
  namespace: v2ns
spec:
  replicas: 5
  selector:
    app: webapp2
  template:
    metadata:
      name: webapp2
      labels:
        app: webapp2
    spec:
      containers:
        - name: javacontainer
          image: smobinulla/nginxmob:v2
          ports:
          - containerPort: 80
---
