apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim1
spec:
storageClassName: gp3
accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVoolumeClaim:
        claimName: task-pv-claim1
  containers:
    - name: nginx-con
      image: nginx
      ports:
      - containerPort: 80
      name: "http-server"
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: task-pv-storageapi
