apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: high
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
