apiVersion: v1
kind: PersistentVolume
metadata: 
  name: aws-pv1
  labels:
    type: aws-pv1
spec:
  storageClassName: gp3
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-024f303c0c62c7dd5
    fsType: ext4
