apiVersion: v1
kind: PersistentVolume
metadata: 
  name: aws-pv2
  labels:
    type: aws-pv2
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-07a9dafab09833b82
    fsType: ext4
