apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv1-claim1
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv2-claim2
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv3-claim3
spec:
  storageClassName: io1
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 4Gi
