apiVersion: v1
kind: PersistentVolume
metadata: 
  name: aws-pv1
  labels:
    type: aws-pv1
spec:
  storageClassName: gp3
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0a39f2b4114124c27
    fsType: ext4
---      
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: aws-pv2
  labels:
    type: aws-pv2
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-07a9dafab09833b82
    fsType: ext4
---      
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: aws-pv3
  labels:
    type: aws-pv3
spec:
  storageClassName: io1
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 4Gi
  accessModes:
    - ReadOnlyMany
  awsElasticBlockStore:
    volumeID: vol-006ba9cc446d3e5d9
    fsType: ext4
